List<Map<String, dynamic>> Users = [
  {
    "role": "trainee",
    "username": "trainee1",
    "password": "123456789",
    "id": 1,
    "name": "Mustafa Amin",
    "age": 20,
    "email": "mustafa.amin387@gmail.com",
    "phone": "+201125586333",
    "image": "assets/images/mustafa_amin.jpg",
    "weight": 50.0,
    "height": 178.0,
    "contractors": [
      {
        "role": "trainer",
        "username": "MostafaLotfy51",
        "password": "123456789",
        "id": 1,
        "name": "Mostafa Lotfy",
        "age": 20,
        "email": "mostafa.lotfy@gmail.com",
        "phone": "+201145589634",
        "image": "assets/images/Trainer_avatar.png",
        "weight": 70.0,
        "height": 174.0,
        "trainClass": "Fitness",
        "biography": "no biography yet",
        "yearsOfExp": 3,
      },
      {
        "role": "trainer",
        "username": "Moaaz22",
        "password": "123456789",
        "id": 1,
        "name": "Moaaz Mohammed",
        "age": 18,
        "email": "Moaaz.mohammed@gmail.com",
        "phone": "+201145589634",
        "image": "assets/images/Trainer_avatar.png",
        "weight": 60.0,
        "height": 160.0,
        "trainClass": "Fitness",
        "biography": "no biography yet",
        "yearsOfExp": 1,
      },
    ],
  },
  {
    "role": "trainer",
    "username": "MostafaLotfy51",
    "password": "123456789",
    "id": 1,
    "name": "Mostafa Lotfy",
    "age": 20,
    "email": "mostafa.lotfy@gmail.com",
    "phone": "+201145589634",
    "image": "assets/images/Trainer_avatar.png",
    "weight": 70.0,
    "height": 174.0,
    "trainClass": "Fitness",
    "biography": "no biography yet",
    "yearsOfExp": 3,
    "contractors": [
      {
        "role": "trainee",
        "username": "trainee1",
        "password": "123456789",
        "id": 1,
        "name": "Mustafa Amin",
        "age": 20,
        "email": "mustafa.amin387@gmail.com",
        "phone": "+201125586333",
        "image": "assets/images/mustafa_amin.jpg",
        "weight": 50.0,
        "height": 178.0,
        "contractors": []
      }
    ]
  },
  {
    "role": "trainer",
    "username": "Moaaz22",
    "password": "123456789",
    "id": 2,
    "name": "Moaaz Mohammed",
    "age": 18,
    "email": "Moaaz.mohammed@gmail.com",
    "phone": "+201145589634",
    "image": "assets/images/Trainer_avatar.png",
    "weight": 60.0,
    "height": 160.0,
    "trainClass": "Fitness",
    "biography": "no biography yet",
    "yearsOfExp": 1,
    "contractors": []
  },
  {
    "role": "trainer",
    "username": "MahmoudKhaled75",
    "password": "123456789",
    "id": 3,
    "name": "Mahmoud Khaled",
    "age": 23,
    "email": "mahmoud.khaled@gmail.com",
    "phone": "+201145589634",
    "image": "assets/images/Trainer_avatar.png",
    "weight": 58.0,
    "height": 170.0,
    "trainClass": "Fitness",
    "biography": "no biography yet",
    "yearsOfExp": 4,
    "contractors": []
  },
];

List<Map<String, String>> Admins = [
  {"username": "mustafa.amin28", "password": "123456789"},
  {"username": "admin", "password": "123456789"}
];
